from devquest.config import get as config_get

THEMES = {
    "cyberpunk": {
        "name": "Cyberpunk",
        "border": "cyan",
        "accent": "bright_cyan",
        "victory": "green",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim",
        "level_up": "yellow",
        "achievement": "magenta",
        "quest": "cyan",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "green",
        "crit": "yellow",
    },
    "matrix": {
        "name": "Matrix",
        "border": "green",
        "accent": "bright_green",
        "victory": "bright_green",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim green",
        "level_up": "bright_green",
        "achievement": "green",
        "quest": "green",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "green",
        "crit": "bright_green",
    },
    "retro": {
        "name": "Retro",
        "border": "bright_magenta",
        "accent": "magenta",
        "victory": "bright_yellow",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim magenta",
        "level_up": "bright_yellow",
        "achievement": "magenta",
        "quest": "cyan",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "yellow",
        "crit": "bright_yellow",
    },
    "nord": {
        "name": "Nord",
        "border": "bright_blue",
        "accent": "blue",
        "victory": "bright_cyan",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim blue",
        "level_up": "bright_cyan",
        "achievement": "magenta",
        "quest": "blue",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "cyan",
        "crit": "bright_cyan",
    },
    "dracula": {
        "name": "Dracula",
        "border": "magenta",
        "accent": "bright_magenta",
        "victory": "green",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim magenta",
        "level_up": "yellow",
        "achievement": "magenta",
        "quest": "cyan",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "green",
        "crit": "yellow",
    },
    "catppuccin": {
        "name": "Catppuccin",
        "border": "bright_blue",
        "accent": "blue",
        "victory": "green",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim",
        "level_up": "yellow",
        "achievement": "magenta",
        "quest": "cyan",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "green",
        "crit": "yellow",
    },
    "windows95": {
        "name": "Windows 95",
        "border": "blue",
        "accent": "bright_blue",
        "victory": "green",
        "danger": "red",
        "warning": "yellow",
        "muted": "dim blue",
        "level_up": "yellow",
        "achievement": "magenta",
        "quest": "blue",
        "enemy": "red",
        "boss": "bright_red",
        "hit": "green",
        "crit": "yellow",
    },
}


def list_themes() -> list[str]:
    return list(THEMES.keys())


def get_theme(name: str | None = None) -> dict:
    key = name or config_get("theme")
    return THEMES.get(key, THEMES["cyberpunk"])


def theme_color(key: str) -> str:
    return get_theme().get(key, "white")
